"""
Django settings for proyecto_rea project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-la57ga^0#^t1^&+zd)!dahmbt)1aw(j6&4nh)s$8n=93agk754'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rea_api',
    'rest_framework',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_rea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_rea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
AUTH_USER_MODEL = 'rea_api.CustomUser'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'proyecto_rea',       # nombre de tu base en HeidiSQL
        'USER': 'root',         # usuario
        'PASSWORD': 'mario1980',   
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        conn_health_check=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/' 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# proyecto_rea/settings.py

# ... (Dejar el código existente arriba) ...

# ----------------- AUTENTICACIÓN Y SEGURIDAD (Requisitos Tarea) -----------------

# Hashing de contraseñas (Mejora la seguridad por defecto [cite: 35])
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # CORRECT NAME
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',       # CHECK FOR COMMA
    'django.contrib.auth.hashers.Argon2PasswordHasher',       # CHECK FOR COMMA
]

# URLs de redirección (Define el flujo de login/logout)
LOGIN_REDIRECT_URL = 'dashboard'  # Redirige al panel protegido tras el login
LOGOUT_REDIRECT_URL = 'login'     # Redirige al login tras el logout
LOGIN_URL = 'login'               # URL de la vista de login

# Seguridad de Sesiones y Cookies (Buenas Prácticas [cite: 12, 49])
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY' # Previene Clickjacking

# Cookies seguras (Importante para sesiones seguras [cite: 6, 11])
# Usar esto requiere que el sitio se sirva sobre HTTPS en producción
# SESSION_COOKIE_SECURE = True 
# CSRF_COOKIE_SECURE = True 

# Límite de sesiones activas (Control de sesiones [cite: 18])
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14 # Sesión expira en 2 semanas
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # La sesión expira si se cierra el navegador

# ----------------- FIN AUTENTICACIÓN Y SEGURIDAD -----------------

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
